// 此文件为sdp2go工具自动生成,请不要手动编辑

package protocol

type PROTOCOL_RETURN_CODE int32

const (
	SDPSERVERSUCCESS      = 0
	SDPSERVERUNKNOWNERR   = -999990
	SDPSERVERNOFUNCERR    = -999991
	SDPSERVERNOSERVICEERR = -999992
	SDPSERVERQUEUETIMEOUT = -999993
	SDPASYNCCALLTIMEOUT   = -999994
	SDPINVOKETIMEOUT      = -999995
	SDPPROXYCONNECTERR    = -999996
	SDPSERVEROVERLOAD     = -999997
	SDPADAPTERNULL        = -999998
	MFW_UNKNOWN           = -900001
	MFW_INVALID_PARAM     = -900002
)

func (en PROTOCOL_RETURN_CODE) String() string {
	ret := ""
	switch en {
	case SDPSERVERSUCCESS:
		ret = "SDPSERVERSUCCESS"
	case SDPSERVERUNKNOWNERR:
		ret = "SDPSERVERUNKNOWNERR"
	case SDPSERVERNOFUNCERR:
		ret = "SDPSERVERNOFUNCERR"
	case SDPSERVERNOSERVICEERR:
		ret = "SDPSERVERNOSERVICEERR"
	case SDPSERVERQUEUETIMEOUT:
		ret = "SDPSERVERQUEUETIMEOUT"
	case SDPASYNCCALLTIMEOUT:
		ret = "SDPASYNCCALLTIMEOUT"
	case SDPINVOKETIMEOUT:
		ret = "SDPINVOKETIMEOUT"
	case SDPPROXYCONNECTERR:
		ret = "SDPPROXYCONNECTERR"
	case SDPSERVEROVERLOAD:
		ret = "SDPSERVEROVERLOAD"
	case SDPADAPTERNULL:
		ret = "SDPADAPTERNULL"
	case MFW_UNKNOWN:
		ret = "MFW_UNKNOWN"
	case MFW_INVALID_PARAM:
		ret = "MFW_INVALID_PARAM"
	}
	return ret
}
